/*--
* @File Name          : LMS_CreateItemController_Test
* @Summary            : Test class for LMS_CreateItemController
* @Created On         : 02 Oct 2020
* @Created By         : sapan Khandelwal
* @Modification Log   : (Name  -  Date  -  Issue  -  Change Summary)
========================================================================
========================================================================
--*/

@isTest
public class LMS_CreateItemController_Test {

    
     @isTest static void testMethod1()
 {
     //just check the Record types
     LMS_CreateItemController.getRecordTypesMap();
     
 }
}